# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.11.2"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: EXECUTAR TESTES
      run: |
        coverage run -m app_test.py

    - name: Test with pytest
      run: |
        pytest

    - name: reporta
      run: |
        coverage report
